name: 'Rust PR Diff Analyzer'
description: 'Analyze and limit PR size by distinguishing production code from test code using Rust AST analysis'
author: 'RAprogramm'

branding:
  icon: 'code'
  color: 'orange'

inputs:
  max_prod_units:
    description: 'Maximum number of production units allowed'
    required: false
    default: '30'
  max_weighted_score:
    description: 'Maximum weighted score allowed'
    required: false
    default: '100'
  fail_on_exceed:
    description: 'Fail the action if limits are exceeded'
    required: false
    default: 'true'
  output_format:
    description: 'Output format (github, json, human)'
    required: false
    default: 'github'
  config_file:
    description: 'Path to configuration file'
    required: false
    default: ''

outputs:
  prod_functions_changed:
    description: 'Number of production functions changed'
    value: ${{ steps.analyze.outputs.prod_functions_changed }}
  prod_structs_changed:
    description: 'Number of production structs changed'
    value: ${{ steps.analyze.outputs.prod_structs_changed }}
  prod_other_changed:
    description: 'Number of other production units changed'
    value: ${{ steps.analyze.outputs.prod_other_changed }}
  test_units_changed:
    description: 'Number of test units changed'
    value: ${{ steps.analyze.outputs.test_units_changed }}
  prod_lines_added:
    description: 'Lines added in production code'
    value: ${{ steps.analyze.outputs.prod_lines_added }}
  prod_lines_removed:
    description: 'Lines removed from production code'
    value: ${{ steps.analyze.outputs.prod_lines_removed }}
  test_lines_added:
    description: 'Lines added in test code'
    value: ${{ steps.analyze.outputs.test_lines_added }}
  test_lines_removed:
    description: 'Lines removed from test code'
    value: ${{ steps.analyze.outputs.test_lines_removed }}
  weighted_score:
    description: 'Weighted score of changes'
    value: ${{ steps.analyze.outputs.weighted_score }}
  exceeds_limit:
    description: 'Whether limits were exceeded'
    value: ${{ steps.analyze.outputs.exceeds_limit }}

runs:
  using: 'composite'
  steps:
    - name: Get PR diff
      id: get_diff
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff origin/${{ github.base_ref }}...HEAD > /tmp/pr_diff.txt
        else
          git diff HEAD~1 > /tmp/pr_diff.txt
        fi

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build analyzer
      shell: bash
      run: |
        cd ${{ github.action_path }}
        cargo build --release

    - name: Run analysis
      id: analyze
      shell: bash
      run: |
        ARGS="--diff-file /tmp/pr_diff.txt"
        ARGS="$ARGS --max-units ${{ inputs.max_prod_units }}"
        ARGS="$ARGS --max-score ${{ inputs.max_weighted_score }}"
        ARGS="$ARGS --format ${{ inputs.output_format }}"

        if [ -n "${{ inputs.config_file }}" ]; then
          ARGS="$ARGS --config ${{ inputs.config_file }}"
        fi

        OUTPUT=$(${{ github.action_path }}/target/release/rust-diff-analyzer $ARGS)

        echo "$OUTPUT"

        if [ "${{ inputs.output_format }}" = "github" ]; then
          echo "$OUTPUT" >> $GITHUB_OUTPUT
        fi

        if [ "${{ inputs.fail_on_exceed }}" = "true" ]; then
          if echo "$OUTPUT" | grep -q "exceeds_limit=true"; then
            echo "::error::Production code changes exceed configured limits"
            exit 1
          fi
        fi
